### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by alexgorbatchev** [hayes/just-debounce#4]
Please add tests.

**Comment by hayes** [comment]
oh weird, I'll try to find some time to do that today, I think I wrote them at one point, but can't seem to find them, thanks for letting me know!

**Comment by alexgorbatchev** [comment]
Thanks buddy! A `1.0.0` would be super awesome as well, the code seems pretty stable now.

**Comment by hayes** [comment]
published with tests as 1.0.0

**Comment by hayes** [comment]
feel free to reopen if you think tests need to be better, they were a bit rushed

**Comment by alexgorbatchev** [comment]
Epic, thank you! :+1:
